// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var API_BASE = "https://tripup-backend.vercel.app/api/v1";
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List all published TripUp Studio travel-growth services with their titles, categories, slugs, and descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const res = await fetch(`${API_BASE}/travel-services`);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch services: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const items = (json?.data ?? []).map((s) => ({
      title: s.title,
      slug: s.slug,
      category: s.category,
      description: s.description,
      comingSoon: s.comingSoon ?? false
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/list-case-studies.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var API_BASE2 = "https://tripup-backend.vercel.app/api/v1";
var list_case_studies_default = defineTool2({
  name: "list_case_studies",
  title: "List case studies",
  description: "List published TripUp Studio case studies with title, slug, category, and summary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const res = await fetch(`${API_BASE2}/case-studies`);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch case studies: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const items = (json?.data ?? []).map((c) => ({
      title: c.title,
      slug: c.slug,
      category: c.category,
      summary: c.summary ?? c.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { caseStudies: items }
    };
  }
});

// src/lib/mcp/tools/list-playbooks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var API_BASE3 = "https://tripup-backend.vercel.app/api/v1";
var list_playbooks_default = defineTool3({
  name: "list_playbooks",
  title: "List guides & playbooks",
  description: "List published TripUp Studio guides and playbooks with title, slug, category, and summary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const res = await fetch(`${API_BASE3}/playbooks`);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch playbooks: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const items = (json?.data ?? []).map((p) => ({
      title: p.title,
      slug: p.slug,
      category: p.category,
      summary: p.summary ?? p.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { playbooks: items }
    };
  }
});

// src/lib/mcp/tools/list-travel-insights.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var API_BASE4 = "https://tripup-backend.vercel.app/api/v1";
var list_travel_insights_default = defineTool4({
  name: "list_travel_insights",
  title: "List travel insights",
  description: "List published TripUp Studio travel insight articles with title, slug, category, and summary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const res = await fetch(`${API_BASE4}/travel-insights`);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch travel insights: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const items = (json?.data ?? []).map((i) => ({
      title: i.title,
      slug: i.slug,
      category: i.category,
      summary: i.summary ?? i.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { travelInsights: items }
    };
  }
});

// src/lib/mcp/tools/get-resource.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var API_BASE5 = "https://tripup-backend.vercel.app/api/v1";
var PATHS = {
  service: "travel-services",
  case_study: "case-studies",
  playbook: "playbooks",
  travel_insight: "travel-insights"
};
var get_resource_default = defineTool5({
  name: "get_resource",
  title: "Get resource by slug",
  description: "Fetch the full content of a single TripUp Studio resource by type and slug. Type must be one of: service, case_study, playbook, travel_insight.",
  inputSchema: {
    type: z.enum(["service", "case_study", "playbook", "travel_insight"]).describe("Resource type"),
    slug: z.string().min(1).describe("Slug of the resource")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ type, slug }) => {
    const path = PATHS[type];
    const res = await fetch(`${API_BASE5}/${path}/slug/${encodeURIComponent(slug)}`);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch ${type} "${slug}": ${res.status}` }], isError: true };
    }
    const json = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(json?.data ?? json, null, 2) }],
      structuredContent: { resource: json?.data ?? json }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rjeovtycgbjgpqkqeaod";
var mcp_default = defineMcp({
  name: "tripup-studio-mcp",
  title: "TripUp Studio MCP",
  version: "0.1.0",
  instructions: "Tools for browsing TripUp Studio's travel-growth services, case studies, guides & playbooks, and travel insights. Use `list_*` to discover resources, then `get_resource` with the returned slug to fetch full content.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, list_case_studies_default, list_playbooks_default, list_travel_insights_default, get_resource_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
